#!/bin/bash

##################################################
# Created By : Jacque Montague Raymer            #
# Owner/Developer on MakuluLinux Copyright @2014 #
# Website : www.makululinux.com                  #
# Email : raymerjacque@gmail.com                 #
##################################################

#Check current User
username=${USER:=$(/usr/bin/id -run)}

# Define server URLs
SERVER1="http://makululinux.eu"
SERVER2="http://makulu.mooo.com"

# Define directory paths for rsync-debian
PATCH_NUMBER_PATH="/rsync-debian/x/patch-number/"
DEBS_PATH="/rsync-debian/x/debs/"
FILES_PATH="/rsync-debian/x/files/"

# Define a function to sync from the server
sync_from_server() {
    local SERVER_URL=$1
    echo "Attempting to sync from $SERVER_URL..."

    # Sync over the patch-number file
    wget -r -nH -l1 -q --no-parent --reject "index.html*" "${SERVER_URL}${PATCH_NUMBER_PATH}" /usr/share/MakuluSetup/rsync-debian/x/patch-number/ --show-progress | zenity --progress --pulsate --title="Checking Existing Patches" --text="Checking Existing Patches, Be Patient..." --width=300 --no-cancel --auto-close

    # Check if the patch-number sync succeeded
    if [[ $? -ne 0 ]]; then
        echo "Sync from $SERVER_URL (patch-number) failed."
        return 1
    fi

    # Sync over the Deb files
    wget -r -nH -l5 -q --no-parent --reject "index.html*" "${SERVER_URL}${DEBS_PATH}" /usr/share/MakuluSetup/rsync-debian/x/debs/ --show-progress | zenity --progress --pulsate --title="Downloading Patches" --text="Downloading Large Files, This can take a while, Please Be Patient..." --width=500 --no-cancel --auto-close
    
    # Check if the Deb sync succeeded
    if [[ $? -ne 0 ]]; then
        echo "Sync from $SERVER_URL (debs) failed."
        return 1
    fi

    # Sync over the patch files
    wget -r -nH -l5 -q --no-parent --reject "index.html*" "${SERVER_URL}${FILES_PATH}" /usr/share/MakuluSetup/rsync-debian/x/files/ --show-progress | zenity --progress --pulsate --title="Downloading Patches" --text="Downloading Smaller Files, This can take a while, Please Be Patient..." --width=500 --no-cancel --auto-close
    
    # Check if the patch files sync succeeded
    if [[ $? -ne 0 ]]; then
        echo "Sync from $SERVER_URL (files) failed."
        return 1
    fi
    
    echo "Sync from $SERVER_URL successful."
    return 0
}

#### Lets Change Directories
cd /usr/share/MakuluSetup/

#### Lets remove old patch Directories
rm -rf /usr/share/MakuluSetup/rsync-debian/*

#### Try syncing from SERVER1, if it fails, try SERVER2
sync_from_server "$SERVER1" || sync_from_server "$SERVER2"

#### Remove any rogue index files
find . -name index??* -delete --show-progress | zenity --progress --pulsate --title="Updating Sources" --text="Removing Junk Files, Be Patient..." --width=300 --no-cancel --auto-close

exit 0

####################
